### ISSUE TITLE
Can you include a requirements.txt file?

### ISSUE THREAD

**Issue by smoosh911** [vonclites/squeezenet#8]
I am not able to import slim. What is this and where did you find this library?

**Comment by muthiyanbhushan** [comment]
This library is in models/research folder in the tensorflow/models original github.
Just download and the path to your pythonpath. 
I accomplished it y

import sys
sys.path.append("/home/user/models/research")

Link to models Github:

https://github.com/tensorflow/models

Thanks.

Hope it helps.

**Comment by vonclites** [comment]
Unfortunately the requirements.txt file would not help this issue, since you cannot do a simple pip install slim.  I will add instructions to the readme as soon as I get a chance, or will accept a pull request.

I've been wanting to create an independent version of their deployment module for a while now but haven't gotten around to it.

**Comment by smoosh911** [comment]
thanks guys
